# Generated by Django 5.1.15 on 2026-05-04 06:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to supplier'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('temu_order_id', models.CharField(blank=True, db_index=True, help_text="Temu's own order ID, when linked.", max_length=64)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('ordered_at', models.DateTimeField(blank=True, help_text='Set when status moves DRAFT -> SENT.', null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('internal_id_code', models.CharField(blank=True, db_index=True, help_text='Client-internal short code (e.g. 10D, 11D).', max_length=32)),
                ('alternative_id_code', models.CharField(blank=True, help_text='Alternative supplier SKU.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('item_size', models.CharField(blank=True, max_length=64)),
                ('colour', models.CharField(blank=True, max_length=128)),
                ('finish', models.CharField(blank=True, max_length=128)),
                ('shape', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sub_brand', models.CharField(blank=True, help_text='Sub-brand of supplier (e.g. EFREY, SUPERDANT).', max_length=64)),
                ('unit', models.CharField(choices=[('piece', 'pieces'), ('gram', 'grams'), ('kg', 'kilograms'), ('metre', 'metres'), ('cm', 'centimetres'), ('ml', 'millilitres'), ('litre', 'litres'), ('strand', 'strands'), ('pack', 'packs'), ('set', 'sets'), ('other', 'other')], default='piece', max_length=16)),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('pack_size', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Units per supplier pack.', max_digits=14)),
                ('last_paid_pack_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Most recent pack cost (ZAR).', max_digits=12)),
                ('import_duties_per_pack', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('last_paid_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Effective unit cost = (pack_cost + duties) / pack_size. Used for COGS.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('typical_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code from the spreadsheet, e.g. SBR00EARR.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pillar', models.CharField(choices=[('BODY_ADORNMENTS', 'Body Adornments'), ('SACRED_TOOLS', 'Sacred Tools'), ('BAMBOO_CLOTHING', 'Bamboo Clothing'), ('OTHER', 'Other')], default='BODY_ADORNMENTS', max_length=24)),
                ('default_retail_price_zar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand')),
            ],
            options={
                'ordering': ('brand', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Sellable SKU, e.g. SBR01-EARR.', max_length=64, unique=True)),
                ('retail_price_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Override of Product.default_retail_price_zar. Blank = use product default.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'ordering': ('product', 'variant'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.PositiveIntegerField()),
                ('quantity_made', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_items', to='inventory.productvariant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.project')),
            ],
            options={
                'ordering': ('project', 'product_variant'),
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='inventory.productvariant')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='inventory.project')),
                ('project_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='inventory.projectitem')),
            ],
            options={
                'ordering': ('-run_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Units per pack ordered.', max_digits=14)),
                ('pack_count', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Number of packs ordered.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Effective unit cost (ZAR).', max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('purchase_order', 'raw_material'),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_zar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('WEBSITE', 'Website (DTC)'), ('IN_PERSON', 'In person'), ('SUGAR_BUSH', 'Sugar Bush'), ('MARKET', 'Market / pop-up'), ('WHOLESALE', 'Wholesale'), ('GIFT', 'Gift / promo'), ('OTHER', 'Other')], db_index=True, default='WEBSITE', max_length=16)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.productvariant')),
            ],
            options={
                'ordering': ('-sale_date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.brand')),
            ],
            options={
                'ordering': ('brand', 'code'),
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='inventory.variant'),
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.productvariant')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('product_variant', 'raw_material'),
                'unique_together': {('product_variant', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reason', models.CharField(choices=[('PO_RECEIVED', 'Purchase order received'), ('PRODUCTION_CONSUMED', 'Production run consumed'), ('ADJUSTMENT', 'Manual adjustment'), ('INITIAL_STOCK', 'Initial / opening stock')], max_length=32)),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['raw_material', '-created_at'], name='inventory_s_raw_mat_77ce58_idx'), models.Index(fields=['reason', '-created_at'], name='inventory_s_reason_748aca_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant')},
        ),
    ]
