# Generated by Django 5.1.15 on 2026-05-02 15:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pillar', models.CharField(choices=[('BODY_ADORNMENTS', 'Body Adornments'), ('SACRED_TOOLS', 'Sacred Tools'), ('BAMBOO_CLOTHING', 'Bamboo Clothing'), ('OTHER', 'Other')], default='BODY_ADORNMENTS', max_length=24)),
                ('retail_price_zar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pillar', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to supplier'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('piece', 'pieces'), ('gram', 'grams'), ('kg', 'kilograms'), ('metre', 'metres'), ('cm', 'centimetres'), ('ml', 'millilitres'), ('litre', 'litres'), ('strand', 'strands'), ('pack', 'packs'), ('set', 'sets'), ('other', 'other')], default='piece', max_length=16)),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Denormalised running total. Reconcilable from StockMovement log.', max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='When current_stock <= this, the material flags as needing reorder.', max_digits=14)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suggested order quantity when below reorder_point.', max_digits=14)),
                ('last_paid_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Most recent unit cost paid (ZAR). Used for COGS calculation.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('typical_lead_time_days', models.PositiveIntegerField(blank=True, help_text='Average days from order placed to receipt.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of finished units produced.')),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='inventory.product')),
            ],
            options={
                'ordering': ('-run_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('purchase_order', 'raw_material'),
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of raw_material consumed per unit of product.', max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('product', 'raw_material'),
                'unique_together': {('product', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=4, help_text='Signed change to current_stock. Positive = received, negative = consumed.', max_digits=14)),
                ('reason', models.CharField(choices=[('PO_RECEIVED', 'Purchase order received'), ('PRODUCTION_CONSUMED', 'Production run consumed'), ('ADJUSTMENT', 'Manual adjustment'), ('INITIAL_STOCK', 'Initial / opening stock')], max_length=32)),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['raw_material', '-created_at'], name='inventory_s_raw_mat_77ce58_idx'), models.Index(fields=['reason', '-created_at'], name='inventory_s_reason_748aca_idx')],
            },
        ),
    ]
