# Generated by Django 5.1.15 on 2026-05-09 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], db_index=True, max_length=16)),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('object_pk', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='SKU/code of the changed object, if applicable.', max_length=128)),
                ('field', models.CharField(blank=True, max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['model_name', 'object_pk'], name='inventory_d_model_n_cb3c9b_idx'), models.Index(fields=['sku', '-timestamp'], name='inventory_d_sku_162d0a_idx')],
            },
        ),
    ]
