# Generated by Django 5.1.15 on 2026-05-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_datachangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
